language: node_js
node_js:
  - "0.12"
before_script:
  # Install Testspace Runner
  - ./testspace_install.sh
  - export PATH="${HOME}/testspace:${PATH}"
  - npm install -g gulp
  
script: 
  - gulp build
# Publish Test Results along with Coverage
  - testspace publish [Tests]test/reports/junitresults.xml{test} test/reports/coverage/clover.xml ${TESTSPACE_URL}
