language: node_js
node_js:
  - "4.0"
  
before_script:
  - npm install -g gulp
  - npm install
  
script: 
  - gulp build
  
  - export CI_REPORTS=$PWD/test/reports
  - curl -s https://testspace-client.s3.amazonaws.com/testspace-linux.tgz | sudo tar -zxvf- -C /usr/local/bin
  - testspace publish @.testspace $TESTSPACE_TOKEN/${TRAVIS_BRANCH}#travis.Build.${TRAVIS_BUILD_NUMBER}
  