language: node_js
node_js:
  - "4.0"
  
before_script:
  - mkdir -p $HOME/bin
  - curl -fsSL https://testspace-client.s3.amazonaws.com/testspace-linux.tgz | tar -zxvf- -C $HOME/bin
  - testspace config url samples.testspace.com
  - npm install -g gulp
  - npm install
  
script: 
  - gulp build
  
# refer to ".testspace.txt" for list of content
after_script:
  - testspace @.testspace.txt
