language: node_js
node_js:
  - "4.0"
  
before_script:
  - npm install -g gulp
  - npm install
  
script: 
  - gulp build
  
# Requires TESTSPACE_TOKEN environment variable.   
after_script:
  - curl -s https://testspace-client.s3.amazonaws.com/testspace-linux.tgz | sudo tar -zxvf- -C /usr/local/bin
  - testspace @.testspace.txt $TESTSPACE_TOKEN/${TRAVIS_REPO_SLUG/\//:}/${TRAVIS_BRANCH}#travis.Build.${TRAVIS_BUILD_NUMBER}
